env = Environment(CCFLAGS='-w')
# Library paths
lib_path = ['/usr/local/lib', '/usr/lib']
# Library names
libs = ['pcap']
# Header file path
cpp_path=[]

env.Program(target = './tracecap', 
			source = './src/main.c',
			LIBS = libs,
			LIBPATH = lib_path,
			CPPPATH = cpp_path)
		
